# Generated by Django 4.1 on 2022-09-11 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_book_book_android_link_vote_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_favourite_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to='mainsite.vote'),
        ),
    ]
